### ISSUE TITLE
Auto trigger when action on terminal

### ISSUE THREAD

**Issue by bouteillerAlan** [ofirgall/tmux-window-name#18]
This is not a bug, this is a question.

When I open or close neovim for example or change folders with `cd` the window names are not updated (I only have one `pan` on each window).

To update the title I have to refocus a window, by pressing ctrl+b and 1 for example.

Is there a way to make it update automatically?

**Comment by ofirgall** [comment]
Hey, I have added explanation in the [README](https://github.com/ofirgall/tmux-window-name#automatic-rename-after-changing-dir)
