### ISSUE TITLE
Support libtmux > 0.16

### ISSUE THREAD

**Issue by itsjfx** [ofirgall/tmux-window-name#20]
hey there,

I just fired up this project after it looked exactly what I was after
however it seems to be flodding the terminal with this output everytime it runs (using the `cd` hook):

```bash
/home/jfx/.local/lib/python3.10/site-packages/libtmux/server.py:581: UserWarning: Server._list_panes() is deprecated
  warnings.warn("Server._list_panes() is deprecated")
/home/jfx/.local/lib/python3.10/site-packages/libtmux/session.py:642: UserWarning: Session._list_windows() is deprecated
  warnings.warn("Session._list_windows() is deprecated"
```

the two methods seem to be deprecated in these commits:

- <https://github.com/tmux-python/libtmux/commit/7449df207647b55b5b89da38f722f47e0b9b72ea>
- <https://github.com/tmux-python/libtmux/commit/373973b2c59d9193677d6db478106c3a74662c2c>

it looks like a fix is using self.panes and self.windows attributes on the server and session respectively

**Comment by ofirgall** [comment]
Hey, I have tried to upgrade to libtmux 0.18 but its not that simple, I'll do it later.
You can install libtmux 0.16 for now
```bash
python3 -m pip install libtmux==0.16
```

**Comment by itsjfx** [comment]
Thanks, `0.16` is working as expected :)

**Comment by kohane27** [comment]
Currently `tmux-window-name` is incompatible with [tmuxp](https://github.com/tmux-python/tmuxp).

```
tmuxp --version
tmuxp 1.27.0, libtmux 0.21.0
```

Hopefully `tmux-window-name` can remove the `libtmux` dependency of `0.16.1` and so I can enjoy `tmux-window-name` again. Thank you in advance!

**Comment by ofirgall** [comment]
@kohane27 I have upgraded the plugin to work with the newest `libtmux` (0.21.1).
