### ISSUE TITLE
empty `ps -a -oppid,command` results in crash

### ISSUE THREAD

**Issue by itsjfx** [ofirgall/tmux-window-name#21]
Hey there,

I noticed behaviour where if I have a tmux session with multiple windows and just `zsh` running (no programs) -- when switching windows repeatedly I'd receive errors from `tmux` that the script exited with code `1`

it was difficult to replicate invoking the script directly

I added some logging and noticed these exceptions were getting fired

`Command '['ps', '-a', '-oppid,command']' returned non-zero exit status 1.{'returncode': 1, 'cmd': ['ps', '-a', '-oppid,command'], 'output': b'   PPID COMMAND\n', 'stderr': None`

After applying the following change everything seems OK :) -- but may want something cleaner?

```diff
diff --git a/scripts/rename_session_windows.py b/scripts/rename_session_windows.py
index 30789d5..77951e9 100755
--- a/scripts/rename_session_windows.py
+++ b/scripts/rename_session_windows.py
@@ -194,7 +194,10 @@ def rename_window(server: libtmux.Server, window_id: str, window_name: str, max_
 
 def get_panes_programs(session: libtmux.Session, options: Options):
     session_active_panes = get_session_active_panes(session)
-    running_programs = subprocess.check_output(['ps', '-a', '-oppid,command']).splitlines()[1:]
+    try:
+        running_programs = subprocess.check_output(['ps', '-a', '-oppid,command']).splitlines()[1:]
+    except subprocess.CalledProcessError:
+        running_programs = []
 
     return [Pane(p, get_current_program(running_programs, int(p['pane_pid']), options)) for p in session_active_panes]
 
```

**Comment by itsjfx** [comment]
and even minorer issue

`run-shell ~/clone/path/tmux-window-name.tmux` in README.md should be `tmux_window_name.tmux`

**Comment by ofirgall** [comment]
The solution is fine by me, can you open a PR?
