### ISSUE TITLE
bug: python version compatibility issue with f-string syntax

### ISSUE THREAD

**Issue by joyme123** [ofirgall/tmux-window-name#30]
Some debug code with f-string syntanx {xxxx=}:

```python
logging.debug(f'{program=} {program_name=} {program_name_stripped=}')
```

this feature needs python3.8+, but readme says:

- Python 3.6.8+ (Maybe can be lower, tested on 3.6.8)

I think f-string syntanx `{xxxx=}` should be used here. Because most of system default python3 version is lower than 3.8.

ref documents: https://docs.python.org/3.8/whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging

**Comment by ofirgall** [comment]
Thanks for the issue and the PR!
