### ISSUE TITLE
Is it possible to show the command without its arguments?

### ISSUE THREAD

**Issue by liangkarl** [ofirgall/tmux-window-name#35]
As the title says, is it possible to show the command without its arguments?

since I know what I'm doing while opening a new `tmux` window, it's unnecessary for me to show the full commands in each window name. It's enough for me that only shows the command name without its arguments, like `vim ~/foo/foo.txt` becoming `vim`. Is it possible to do this? Thanks~

**Comment by ofirgall** [comment]
Hey, I have pushed an update that add an option to disable arguments.

https://github.com/ofirgall/tmux-window-name?tab=readme-ov-file#tmux_window_name_show_program_args

**Comment by liangkarl** [comment]
Thanks! : )
