### ISSUE TITLE
python regexp: invalid escape sequence \g

### ISSUE THREAD

**Issue by rNoz** [ofirgall/tmux-window-name#37]
I use this plugin in some different machines, but it is the first time seeing this error.

```shell
$ cd any-dir
/home/user/.tmux/plugins//tmux-window-name/scripts/rename_session_windows.py:125: SyntaxWarning: invalid escape sequence '\g'
  substitute_sets: List[Tuple] = field(default_factory=lambda: [(r'.+ipython([32])', r'ipython\g<1>'), USR_BIN_REMOVER, (r'(bash) (.+)/(.+[ $])(.+)', '\g<3>\g<4>')])
```

My machine:

ABI             : arm64-little_endian-lp64
Kernel          : linux 6.8.9-406.asahi.fc40.aarch64+16k
Product         : Fedora Linux Asahi Remix 40 (KDE Plasma)
Tmux : 3.4
Python: 3.12.3
Zsh: 5.9

**Comment by ofirgall** [comment]
Thanks!
