### ISSUE TITLE
Version checking

### ISSUE THREAD

**Issue by jaclu** [ofirgall/tmux-window-name#4]
As is, it runs on tmux 3.0 and higher. 

If I change'session-window-changed[8921]' in `tmux_window_name.tmux` into 'session-window-changed' it works all the way back to version 2.5!

I'm kind of curious, in my testing, it seems to be working perfectly fine without it. 
I have never seen event suffixes like that, care to share what it does? Always fun to learn new stuff!

**Comment by ofirgall** [comment]
When you don't use the `[index]` you are limited by 1 command per hook, I don't want to override someone's hook so I used a random index in the hope it will be unique.
